### ISSUE TITLE
Issues on ubuntu 18 docker.

### ISSUE THREAD

**Issue by gleisonsdm** [chunhualiao/rose-docker-image#1]
Hi,

I am trying to run autoPar after create a Dockerfile with rose, but it seems like the frontend cannot find the include files of C++ in /usr/include (I am using ubuntu 18 and g++-7).

You can access my image on Docker using:
**docker pull gleisonsdm/rose**

I ran the follow command line:
**sudo docker run --rm -it -v $(pwd):/root rose autoPar -c test.cpp**

Here is the file I am using:
```cpp
#include <iostream>

int main() {
  std::cout << "HELLO WORLD.\n";
  return 0;
}
```

Here is the beginning of my error stack:
```bash
gleison@gleison-HP-ENVY-x360-m6-Convertible:~/Desktop/testR$ sudo docker run --rm -it -v $(pwd):/root rose autoPar -c test.cpp
"/usr/rose/include/edg/g++-7_HEADERS/hdrs7/bits/floatn.h", line 75: error:
          invalid argument to attribute "__mode__"
  typedef _Complex float __cfloat128 __attribute__ ((__mode__ (__TC__)));
                                                               ^

"/usr/rose/include/edg/g++-7_HEADERS/hdrs7/bits/byteswap.h", line 37: error:
          identifier "__builtin_bswap16" is undefined
    return __builtin_bswap16 (__bsx);
           ^

"/usr/include/c++/7/bits/move.h", line 48: error: identifier
          "__builtin_addressof" is undefined
      { return __builtin_addressof(__r); }
```

**Comment by chunhualiao** [comment]
@gleisonsdm A co-worker also has a docker image:  https://github.com/tristanvdb/demo-user-rose-docker-workspace. He just added some documentation and verified that autoPar is available.  You can take a look at his and see what went wrong.
