### ISSUE TITLE
instructions not clear after "sudo docker run --rm -it -v $(pwd):/root gleisonsdm/rose sh"

### ISSUE THREAD

**Issue by chunhualiao** [chunhualiao/rose-docker-image#4]
@gleisonsdm I am able to download your docker file. But I got lost after typing "sudo docker run --rm -it -v $(pwd):/root gleisonsdm/rose sh"  

What should users do after that? Where to find rose binaries?  How to use identityTraslator to process a simple hello-world program?

Please refine the readme to reflect these details. 

Thanks!

**Comment by gleisonsdm** [comment]
Hi,

I tried to improve the use instructions. Please, check if it is now easy to understand. If something is not clear, I can work to improve it more.

**Comment by chunhualiao** [comment]
This works! Thanks a lot!
